### ISSUE TITLE
Gimme just sends me to my home directory.

### ISSUE THREAD

**Issue by cmcdowell** [stefanjcollier/Gimme#1]
Whenever I use gimmie, it prints out that the git repo I want has been selected but gimmie just changes my current directory to my home directory.

The following is the code that gimme told me to add to my bashrc during startup

```
function gimme {
   python /Users/cmcdowell/tools/gimme/gimme.py $*
   if [ 0 -eq 0  ]; then
        cd
   fi
}
```

**Comment by stefanjcollier** [comment]
Ah thats an issue with the installer! Seems I forgot to escape some of the variables before echo-ing them!

**Comment by stefanjcollier** [comment]
I should have fixed this with the latest commit (Starting with 'Bugfix#1').
Pull, run the intaller, replace the new function with the old in your bashrc and that should work.
